Fix building issue because of old SDK
This intends to fix this issue:

* What went wrong:
Execution failed for task ':flutter_checkout_payment:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /Users/lucas/meowtel/v4/meowtel-mobile/build/flutter_checkout_payment/intermediates/merged_res/release/values/values.xml:6134: AAPT: error: resource android:attr/lStar not found.